build_image: freedomjs/freedom
language: node_js
node_js:
- 'stable'
- '4.4'
notifications:
  email:
    recipients:
      - freedom@cs.washington.edu
    on_success: change
    on_failure: always
install:
  - "shippable_retry npm install"
script:
  - "grunt test --verbose"
